### ISSUE TITLE
Minimal code cleanup

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-test-utilities#33]
We are already in decent shape but do a pass for general things outlined in the Engineering Plan.

```
rg --pcre2 '(?<!SELECT)(// |^ *\*(?!/))(?! Copyright|.*Apache|.*eslint)'
```

**Comment by nijotz** [comment]
Nothing egregious. A few TODOs that could be addressed about changing some code when Node 0.8 and 0.10 support is dropped, but that's it.
