### ISSUE TITLE
Use npm 'file's list instead of npmignore

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-test-utilities#78]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Feature Description

A clear and concise description of the feature you want or need.

## Describe Alternatives

A clear and concise description of any alternative solutions or features you've considered. Are there examples you could link us to?

## Additional context

Add any other context here.

## Priority

Please help us better understand this feature request by choosing a priority from the following options:
[Nice to Have, Really Want, Must Have, Blocker]

**Comment by bizob2828** [comment]
Done in https://github.com/newrelic/node-test-utilities/pull/81
